### ISSUE TITLE
Request on updateing the support for the second-generation inspire hand

### ISSUE THREAD

**Issue by Charlie0257** [dexsuite/dex-urdf#18]
Hi, @yzqin 
Thanks for this great work!

I found the project has supported the first-generation Inspire Hand :)
Could you update the support for the second-generation Inspire Hand by considering the [Project](https://github.com/Director-of-G/inspire_hand_model)?

Thanks for any help!

Best,
Charlie

**Comment by yzqin** [comment]
Hi @Charlie0257 

I think the inspire hand in the provided link is nearly the same as the one in this repo. I do not think it is the second-generation inspire hand.

**Comment by Charlie0257** [comment]
@yzqin Thanks for your reply!

Please consider the paper——[Learning Granularity-Aware Affordances from Human-Object Interaction for Tool-Based Functional Grasping in Dexterous Robotics](https://arxiv.org/abs/2407.00614).

The inspire tactile hand used in this work doesn't look similar in this repo :(

**Comment by yzqin** [comment]
I do not know how they get the SolidWorks or STEP model for this inspire hand, maybe you can send me the original Solidworks model so that I can make it a URDF.
