### ISSUE TITLE
dexpilot

### ISSUE THREAD

**Issue by kaijieshi7** [dexsuite/dex-urdf#22]
Hi, what does dexpilot mean?

**Comment by yzqin** [comment]
There is no `dexpilot` in this repo. I think you are talking about the dexpilot retargeting in my other repo: https://github.com/dexsuite/dex-retargeting.

The DexPilot is a paper from NVIDIA, which proposed a retargeting method. This term is used in the retargeting repo to refer to a specific retargeting optimizer.
